total 12
drwxrwxr-x  2 agent_t490 agent_t490 4096 Feb 12 23:07 .
drwxrwxr-x 19 agent_t490 agent_t490 4096 Feb 17 23:39 ..
-rwxrwxr-x  1 agent_t490 agent_t490 2204 Feb 12 23:07 install_cli.sh
#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python3}"
BIN_DIR="${T560_BIN_DIR:-$HOME/.local/bin}"
INSTALL_PY=""

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  echo "install error: python executable not found: $PYTHON_BIN" >&2
  exit 1
fi

echo "Installing t560 from: $ROOT_DIR"
if "$PYTHON_BIN" -m pip install --user --no-build-isolation -e "$ROOT_DIR"; then
  INSTALL_PY="$PYTHON_BIN"
else
  echo "User-site install failed. Falling back to repo virtualenv at $ROOT_DIR/.venv"
  if [[ ! -x "$ROOT_DIR/.venv/bin/python" ]]; then
    "$PYTHON_BIN" -m venv --system-site-packages "$ROOT_DIR/.venv"
  fi
  "$ROOT_DIR/.venv/bin/python" -m pip install --no-build-isolation -e "$ROOT_DIR"
  INSTALL_PY="$ROOT_DIR/.venv/bin/python"
fi

mkdir -p "$BIN_DIR"

_shell_name="$(basename "${SHELL:-bash}")"
_rc_file=""
case "$_shell_name" in
  bash)
    _rc_file="$HOME/.bashrc"
    ;;
  zsh)
    _rc_file="$HOME/.zshrc"
    ;;
esac

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  echo "PATH is missing $BIN_DIR"
  if [[ -n "$_rc_file" ]]; then
    if [[ -f "$_rc_file" ]] && rg -F "export PATH=\"$BIN_DIR:\$PATH\"" "$_rc_file" >/dev/null 2>&1; then
      :
    else
      {
        echo ""
        echo "# Added by t560 installer"
        echo "export PATH=\"$BIN_DIR:\$PATH\""
      } >> "$_rc_file"
    fi
    echo "Added PATH export to $_rc_file"
    echo "Run: source $_rc_file"
  else
    echo "Add this to your shell profile manually:"
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
  fi
  export PATH="$BIN_DIR:$PATH"
fi

if [[ -f "$BIN_DIR/t560" ]] && ! grep -q "t560.cli" "$BIN_DIR/t560"; then
  echo "install error: refusing to overwrite unmanaged launcher: $BIN_DIR/t560" >&2
  exit 1
fi

cat > "$BIN_DIR/t560" <<EOF
#!/usr/bin/env bash
# Generated by t560 installer
exec "$INSTALL_PY" -m t560.cli --invoked-as t560 "\$@"
EOF
chmod +x "$BIN_DIR/t560"

if "$BIN_DIR/t560" --version >/dev/null 2>&1; then
  echo "t560 install ok."
  echo "Command available at: $BIN_DIR/t560"
  echo "Run: t560"
else
  echo "install error: t560 command failed smoke test." >&2
  echo "Try: $PYTHON_BIN -m t560.cli --version" >&2
  exit 1
fi
