#!/usr/bin/env bash
set -euo pipefail

# Installs a launcher at ~/.local/bin/t560 so users can run `t560` from any directory.
# Modeled after references/agent/scripts/install_cli.sh (PATH setup + managed launcher safety).

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${T560_BIN_DIR:-$HOME/.local/bin}"
FORCE=0

if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
  shift || true
fi

mkdir -p "$BIN_DIR"

_shell_name="$(basename "${SHELL:-bash}")"
_rc_file=""
case "$_shell_name" in
  bash)
    _rc_file="$HOME/.bashrc"
    ;;
  zsh)
    _rc_file="$HOME/.zshrc"
    ;;
esac

if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  echo "PATH is missing $BIN_DIR"
  if [[ -n "$_rc_file" ]]; then
    if command -v rg >/dev/null 2>&1 && [[ -f "$_rc_file" ]] && rg -F "export PATH=\"$BIN_DIR:\$PATH\"" "$_rc_file" >/dev/null 2>&1; then
      :
    else
      {
        echo ""
        echo "# Added by t560 installer"
        echo "export PATH=\"$BIN_DIR:\$PATH\""
      } >>"$_rc_file"
    fi
    echo "Added PATH export to $_rc_file"
    echo "Run: source $_rc_file"
  else
    echo "Add this to your shell profile manually:"
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
  fi
  export PATH="$BIN_DIR:$PATH"
fi

if [[ -f "$BIN_DIR/t560" ]] && ! grep -q "Generated by t560 installer" "$BIN_DIR/t560"; then
  if [[ "$FORCE" -eq 1 ]]; then
    ts="$(date +%Y%m%d_%H%M%S)"
    backup="$BIN_DIR/t560.bak.$ts"
    mv "$BIN_DIR/t560" "$backup"
    echo "Backed up existing launcher to: $backup"
  else
    echo "install error: refusing to overwrite unmanaged launcher: $BIN_DIR/t560" >&2
    echo "If you're replacing an older t560 launcher, re-run with: bash scripts/install_cli.sh --force" >&2
    exit 1
  fi
fi

cat >"$BIN_DIR/t560" <<EOF
#!/usr/bin/env bash
# Generated by t560 installer
exec "$ROOT_DIR/scripts/t560" "\$@"
EOF
chmod +x "$BIN_DIR/t560"

if (cd "$HOME" && "$BIN_DIR/t560" --version >/dev/null 2>&1); then
  echo "t560 install ok."
  echo "Command available at: $BIN_DIR/t560"
  echo "Run: t560"
else
  echo "install error: t560 command failed smoke test." >&2
  exit 1
fi
